name: develop

on:
  push:
    branches: [
      develop,
      feature/**
    ]


jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Set Short SHA
        id: find_sha
        run: echo ::set-output name=SHORT_TAG::${SHORT_SHA}

      - name: Set up Python 3.11.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Run flake
        run: flake8 --config=.flake8 -v

      - name: Run mypy
        run: mypy app

      - name: Run test database
        run: docker-compose -f tests/docker-compose-tests.yml up -d

      - name: Run tests
        run: POSTGRES_HOST=localhost REDIS_URL=redis://localhost pytest tests